In [1]:
import mxnet as mx
from mxnet import init,nd
from mxnet.gluon import nn

# Different type of initialization

In [3]:
init.Uniform
init.Normal
init.Xavier
init.Zero
init.One
init.Constant

mxnet.initializer.Constant

In [5]:
layer = nn.Conv2D(channels=1,in_channels=1,kernel_size=(3,3))
layer.initialize(init.Xavier())
layer.weight.data()


[[[[ 0.05636501  0.10720772  0.24847925]
   [ 0.39752382  0.11866093  0.41332   ]
   [ 0.05182666  0.4009717  -0.08815584]]]]
<NDArray 1x1x3x3 @cpu(0)>

# Xavier Initialization large number output

In [6]:
layer = nn.Conv2D(channels=512,in_channels=512,kernel_size=(3,3))
layer.initialize(init.Xavier())
layer.weight.data()[0]


[[[ 0.00630558  0.00744513 -0.00590012]
  [-0.00318499 -0.01033202  0.01999258]
  [-0.0226214   0.02366119 -0.01160159]]

 [[-0.0059481  -0.00113977  0.01488703]
  [ 0.01593029  0.00147454 -0.00102179]
  [ 0.00347238 -0.0054713   0.02171864]]

 [[ 0.01715045 -0.02189048 -0.00829784]
  [-0.02106922  0.00756137 -0.02448375]
  [-0.00672377  0.01697394  0.0233291 ]]

 ...

 [[-0.01893761  0.01284147 -0.00975751]
  [-0.02142992 -0.00148998 -0.00093406]
  [ 0.00985651 -0.00277236  0.00710726]]

 [[ 0.00880146 -0.01043105 -0.00261599]
  [-0.00773894  0.01042632 -0.01882804]
  [ 0.00926955  0.00075613  0.01006069]]

 [[ 0.00549796  0.00605232 -0.0150173 ]
  [-0.01781082  0.02513626  0.01330902]
  [-0.01826004  0.01434206  0.0111638 ]]]
<NDArray 512x3x3 @cpu(0)>

# Deferred Initialization

In [7]:
layer = nn.Conv2D(channels=1,kernel_size=(3,3))
layer.weight

Parameter conv3_weight (shape=(1, 0, 3, 3), dtype=<class 'numpy.float32'>)

In [8]:
layer.initialize(init.Xavier())
layer(mx.nd.ones((1,8,224,224)))
layer.weight

Parameter conv3_weight (shape=(1, 8, 3, 3), dtype=<class 'numpy.float32'>)

# Initialize Contex

In [10]:
layer = nn.Conv2D(channels=1,kernel_size=(3,3))
layer.initialize(init.Xavier(),ctx=mx.cpu())

In [11]:
layer(nd.uniform(shape=(1,3,9,9),ctx=mx.cpu()))


[[[[-0.40201202 -0.7018695   0.0178528   0.58707917  0.27301195
    -0.28182262 -0.04585001]
   [-0.2916031  -0.5289639  -0.29903352  0.07407001  0.08028618
     0.3445815  -0.1369451 ]
   [-0.5982169  -0.02556938  0.23767224 -0.13543423 -0.54306304
    -0.27945024 -0.20130059]
   [-0.3011055  -0.6542944  -0.6064335  -0.15215331  0.6870324
     0.33310294  0.12388389]
   [-0.5037831   0.3842859   0.40459839  0.13650626 -0.4143914
    -0.16389099 -0.5943488 ]
   [-0.30062518 -0.06190275  0.03046748 -1.0344568  -0.04781766
     0.00905293 -0.41354978]
   [-0.48301688 -0.08969666  0.1881354   0.5933385   0.35146433
     0.19643752 -0.6188929 ]]]]
<NDArray 1x1x7x7 @cpu(0)>

# Set data

In [13]:
layer.weight.set_data(nd.ones((1,3,3,3),ctx=mx.cpu()))
layer.weight.data()


[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
<NDArray 1x3x3x3 @cpu(0)>

# Exit